'use client'

/**
 * PDF Export Utility for Deep Research Reports
 * Uses jsPDF directly to avoid CSS parsing issues with html2canvas
 */

interface ExportOptions {
  title: string
  query: string
  expandedQueries?: string[]
  content: string
  sources: { url: string; title: string }[]
  queriesExplored?: { query: string; count: number }[]
}

/**
 * Generate and download a PDF from research content using jsPDF directly
 */
export async function exportResearchAsPDF(options: ExportOptions): Promise<void> {
  const { title, query, expandedQueries = [], content, sources, queriesExplored = [] } = options

  // Dynamically import jsPDF
  const { jsPDF } = await import('jspdf')

  // Create PDF document
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  })

  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 20
  const contentWidth = pageWidth - 2 * margin
  let y = margin

  // Helper to add text with word wrap
  const addText = (text: string, fontSize: number, isBold = false, color: [number, number, number] = [0, 0, 0]) => {
    doc.setFontSize(fontSize)
    doc.setFont('helvetica', isBold ? 'bold' : 'normal')
    doc.setTextColor(color[0], color[1], color[2])

    const lines = doc.splitTextToSize(text, contentWidth)
    const lineHeight = fontSize * 0.5

    for (const line of lines) {
      if (y + lineHeight > pageHeight - margin) {
        doc.addPage()
        y = margin
      }
      doc.text(line, margin, y)
      y += lineHeight
    }
    return y
  }

  // Helper to add spacing
  const addSpace = (mm: number) => {
    y += mm
    if (y > pageHeight - margin) {
      doc.addPage()
      y = margin
    }
  }

  // Build date string
  const date = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })

  // Title
  addText(title || 'Deep Research Report', 20, true)
  addSpace(3)
  addText(`Generated by VerifyAI • ${date}`, 10, false, [100, 100, 100])
  addSpace(10)

  // Original Query
  addText('Original Query', 12, true, [76, 29, 149]) // Purple
  addSpace(2)
  addText(`"${query}"`, 11)
  addSpace(10)

  // Expanded Queries
  if (expandedQueries.length > 0) {
    addText(`Expanded Queries (${expandedQueries.length})`, 12, true, [55, 65, 81])
    addSpace(3)
    for (const q of expandedQueries) {
      addText(`• ${q}`, 10, false, [75, 85, 99])
      addSpace(1)
    }
    addSpace(8)
  }

  // Queries Explored
  if (queriesExplored.length > 0) {
    addText('Queries Explored', 12, true, [55, 65, 81])
    addSpace(4)
    for (const q of queriesExplored) {
      addText(`• ${q.query} (${q.count} sources)`, 10, false, [75, 85, 99])
      addSpace(1)
    }
    addSpace(8)
  }

  // Research Report
  addText('Research Report', 14, true)
  addSpace(5)

  // Process content - strip markdown formatting for plain text
  const plainContent = content
    .replace(/\*\*(.*?)\*\*/g, '$1')
    .replace(/\*(.*?)\*/g, '$1')
    .replace(/#{1,6}\s/g, '')
    .replace(/\n{3,}/g, '\n\n')

  addText(plainContent, 10, false, [55, 65, 81])
  addSpace(10)

  // Sources
  if (sources.length > 0) {
    // Add divider line
    doc.setDrawColor(229, 231, 235)
    doc.line(margin, y, pageWidth - margin, y)
    addSpace(8)

    addText(`Sources (${sources.length})`, 12, true, [55, 65, 81])
    addSpace(4)

    sources.forEach((source, index) => {
      addText(`${index + 1}. ${source.title}`, 9, true, [75, 85, 99])
      addSpace(1)
      addText(source.url, 8, false, [99, 102, 241])
      addSpace(3)
    })
  }

  // Footer
  addSpace(10)
  doc.setDrawColor(229, 231, 235)
  doc.line(margin, y, pageWidth - margin, y)
  addSpace(5)
  addText('Generated with VerifyAI Deep Research Mode', 9, false, [156, 163, 175])

  // Save the PDF
  doc.save(`research-report-${Date.now()}.pdf`)
}
